flights/urls.py
from django.urls import path

from .views import (
	FlightListView,
	FlightDetailView,
	FlightUpdateView,
	HomePageView,
	search_results_view,
	contact_view,
	FlightCreateView,
	FlightDeleteView,
	AllFlightView,
	EachFlightDetail,
)

urlpatterns = [
	path('flights/list/', FlightListView.as_view(), name='flights_list'),
	path("flight/<int:pk>/detail/", FlightDetailView.as_view(), name="flight_detail"),
	path("", HomePageView.as_view(), name="home_page"),
	path("search/results/", search_results_view, name="search_results"),
	path("contact/", contact_view, name="contact_form"),
]

# Flight CRUD urls
urlpatterns += [
	path('flight/create/', FlightCreateView.as_view(), name="flight-create"),
	path('flight/<int:pk>/update/', FlightUpdateView.as_view(), name="flight-update"),
	path('flight/<int:pk>/delete/', FlightDeleteView.as_view(), name="flight-delete"),
]

urlpatterns += [
	path('flyways/flights/list', AllFlightView.as_view(), name="admin-flights"),
	path("flyways/flights/<int:pk>/detail/", EachFlightDetail.as_view(), name="admin-flight-details"),
]

flights_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flights.urls')),
    path('passengers/', include('passengers.urls'))
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

flights/models.py
from django.db import models
from datetime import datetime, timedelta
from django.urls import reverse
from django.contrib.auth.models import User

current_time = datetime.now()

class FlightModelManager(models.Manager):
	def refresh_departure_time(self, flights=None):
		qs = Flight.objects.filter(id__gte=1)
		if flights is not None and isinstance(flights, int):
			qs = qs.order_by('-id')[:flights]
		new_time = current_time + timedelta(hours=5)
		objects_refreshed = 0
		for q in qs:
			q.departure = new_time
			print(q.id, q.departure)
			q.save()
			objects_refreshed += 1
		return f"New Time: {new_time} For: {objects_refreshed} flights"


class Flight(models.Model):
	origin = models.CharField(max_length=50)
	destination = models.CharField(max_length=50)
	price = models.DecimalField(decimal_places=2, max_digits=10000)
	departure = models.DateTimeField(default=current_time + timedelta(hours=2))
	duration = models.DurationField(
		help_text="Duration for flight in hh:mm:ss format"
	)

	FLIGHT_STATUS = (
		('m', 'Maintenance'),
		('d', 'Delay'),
		('a', 'Available'),
		('f', 'Full'),
		('c', 'Cancel'),
	)

	status = models.CharField(max_length=1, choices=FLIGHT_STATUS, default='a', help_text="Flight Availability")

	objects = FlightModelManager()

	def __str__(self):
		return f"Flight: {self.origin} to {self.destination}"

	@property
	def has_departed(self):
		if self.departure < current_time.now():
			return True
		return False

	def get_absolute_url(self):
		return reverse("flight_detail", args=[str(self.id)])

	@property
	def departure_format(self):
		return self.departure.strftime("On %A %d %B, %y at %H:%M")

	@property
	def get_departure_time(self):
		departure_in = self.departure - current_time
		return self.departure.time().strftime("%H:%M %p")

	@property
	def get_arrival_time(self):
		arrival_in = self.departure + self.duration
		return arrival_in.strftime("On %A %d %B, %y at %H:%M %p")

flights/forms.py
from django import forms

class ContactForm(forms.Form):
	contact_name = forms.CharField(required=True)
	contact_email = forms.EmailField(required=True)
	content = forms.CharField(
		required=False,
		widget=forms.Textarea)

	def __init__(self, *args, **kwargs):
		super(ContactForm, self).__init__(*args, **kwargs)
		self.fields['contact_name'].label = 'Your name:'
		self.fields['contact_email'].label = 'Your email:'

flights/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template.loader import get_template

from .models import Flight
from .forms import ContactForm

from datetime import datetime

class HomePageView(generic.ListView):
	model = Flight
	template_name = "flights/home_page.html"

	def get_queryset(self):
		return Flight.objects.filter(status__exact="a").filter(departure__gte=datetime.now())[:5]


class FlightListView(generic.ListView):
	model = Flight
	template_name = "flights/flights_list.html"
	
	def get_queryset(self):
		return Flight.objects.filter(status__exact="a").order_by("-departure")


class FlightDetailView(generic.DetailView):
	model = Flight
	template_name = "flights/flight_detail.html"

	def get_queryset(self):
		return Flight.objects.filter(status__exact="a").filter(departure__gte=datetime.now())


def search_results_view(request):
	query = request.GET['search_query']
	context = {
		"query": query
	}
	return render(request, "flights/search_results.html", context)


def contact_view(request):
	contact_form = ContactForm

	if request.method == "POST":
		form = contact_form(data=request.POST)

		if form.is_valid():
			contact_name = request.POST.get('contact_name', '')
			contact_email = request.POST.get('contact_email', '')
			try:
				form_content = request.POST.get('content', '')
			except Exception as e:
				pass

			template = get_template('contact_template.txt')
			context = {
				'contact_name': contact_name,
				'contact_email': contact_email,
				'form_content': form_content
			}

			content = template.render(context)

			email = EmailMessage(
				"New Contact Form Submission",
				content,
				"Your Django App ",
				["pranavg456@gmail.com"],
				headers={'Reply-To': contact_email}
			)

			notify_template = get_template("contact_soon_template.txt")
			notify_context = {
				"flight_detail": "FLIGHT",
				"content": form_content
			}
			notify_content = notify_template.render(notify_context)

			contact_soon_email = EmailMessage(
				"Django Flyways",
				notify_content,
				"Django Flyways Team",
				[contact_email],
			)

			email.send()
			contact_soon_email.send()
			return render(request, 'contact_confirm.html', context)

	return render(request, 'contact_form.html', {'contact_form': contact_form})


# Flights CRUD
class FlightCreateView(LoginRequiredMixin, CreateView):
	model = Flight
	fields = "__all__"


class FlightUpdateView(LoginRequiredMixin, UpdateView):
	model = Flight
	fields = "__all__"


class FlightDeleteView(LoginRequiredMixin, DeleteView):
	model = Flight
	success_url = reverse_lazy('flights_list')


# admin accessible views only
class AllFlightView(LoginRequiredMixin, generic.ListView):
	model = Flight
	template_name = "flights/all_flights_list.html"

	def get_context_data(self, **kwargs):
		context = super(AllFlightView, self).get_context_data(**kwargs)
		context['flight_list_view'] = "True"
		return context


class EachFlightDetail(LoginRequiredMixin, generic.DetailView):
	model = Flight
	template_name = "flights/each_flight_detail.html"

	def get_context_data(self, **kwargs):
		context = super(EachFlightDetail, self).get_context_data(**kwargs)
		context['flight_detail_view'] = "True"
		return context

templates/flights/all_flights_list.html
{% extends "base.html" %}

{% block title %}
	All Flights List - Admin View
{% endblock title %}

{% block content %}
	<!-- SECTION: FLIGHTS -->
    <div class="mt-5 mb-5 container">
    	{% for flight in flight_list %}
	    
	    	<!--Panel-->
	    	<div class="card w-75 mb-4">
		        <div class="card-body">
		            <h5 class="card-title">₹ {{ flight.price }}</h5>
		            <p class="card-text">Cheapest flight from {{ flight.origin }} to {{ flight.destination }}</p>

		            <a href="{% url 'admin-flight-details' flight.pk %}" class="btn {% if flight.has_departed %}btn-danger{% else %}btn-success{% endif %}">Details</a>

		        </div>
		        <div class="card-footer">
		            <small class="text-muted">
		            	{% if flight.has_departed %}
		            		Departed...
		            	{% else %}
		            	 	Departure on {{ flight.get_departure_time }}...
						{% endif %}
		            </small>
		        </div>
			</div>
			<!--/.Panel-->
		
		{% endfor %}
	</div>

	<!-- /SECTION: FLIGHTS -->
{% endblock content %}

templates/flights/contact_form.html
{% extends "base.html" %}

{% block title %}
	Get Notified
{% endblock %}

{% block content %}
	
	<!--Section: Contact v.2-->
	<section class="section">

	    <!--Section heading-->
	    <h2 class="h1-responsive font-weight-bold text-center my-5">Get Notified</h2>
	    <!--Section description-->
	    <p class="text-center w-responsive mx-auto mb-5">The flight you are looking for has been departed, we can notify you when the flight is available.</p>

	    <div class="row">

	    	<div class="col-md-3"></div>

	        <!--Grid column-->
	        <div class="col-md-6 mb-md-0 mb-5">
	            <form id="contact-form" name="contact-form" action="{% url 'contact_form' %}" method="POST">

	            	{% csrf_token %}

	                <!--Grid row-->
	                <div class="row">

	                    <!--Grid column-->
	                    <div class="col-md-6">
	                        <div class="md-form mb-0">
	                            <input type="text" id="name" name="name" class="form-control">
	                            <label for="name" class="">Your name</label>
	                        </div>
	                    </div>
	                    <!--Grid column-->

	                    <!--Grid column-->
	                    <div class="col-md-6">
	                        <div class="md-form mb-0">
	                            <input type="text" id="email" name="email" class="form-control">
	                            <label for="email" class="">Your email</label>
	                        </div>
	                    </div>
	                    <!--Grid column-->

	                </div>
	                <!--Grid row-->

	            </form>

	            <div class="text-center text-md-left">
	                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
	            </div>
	            <div class="status"></div>
	        </div>
	        <!--Grid column-->

	    	<div class="col-md-3"></div>


	    </div>

	</section>
	<!--Section: Contact v.2-->

{% endblock %}

templates/flights/contact_form_submit.html
{% extends "base.html" %}

{% block title %}
	Contact Form Submitted
{% endblock %}

{% block content %}

<div class="container mt-5">
	<h3 class="green-text">Thanks {{ contact_name }}!</h3>
	<h5 class="grey-text">You will be notified at {{ contact_email }}</h5>
</div>

{% endblock %}

templates/flights/each_flight_detail.html
{% extends "base.html" %}

{% block title %}
	Flights Detail
{% endblock title %}

{% block content %}
	<!-- SECTION: FLIGHTS -->
	<section class="container mt-5">
		
		<h3 class="red-text text-left pl-3 mb-4">
			{% if flight.has_departed %}
				Flight has been departed
			{% else %}
				Flight is available
			{% endif %}
		</h3>
		
		<!-- ROW STARTS -->
		<div class="row container">

			<!-- COL STARTS -->
			<div class="col-md-4 text-left">
				<h4>From: <span class="green-text">{{ flight.origin|title }}</span></h4>
			</div>
			<!-- COL ENDS -->

			<!-- COL STARTS -->
			<div class="col-md-4 text-left">
				<h4>To: <span class="green-text">{{ flight.destination|title }}</span></h4>
			</div>
			<!-- COL ENDS -->

			<!-- COL STARTS -->
			<div class="col-md-4 text-left">
				<h4>Duration: <span class="grey-text">{{ flight.duration }}<span></h4>
			</div>
			<!-- COL ENDS -->

			<!-- ROW STARTS -->
			<div class="row container mt-3">

				<!-- COL STARTS -->
				<div class="col-md-12 mb-3 text-left">
					<h4>Departure from {{ flight.origin }}: <span class="blue-text">{{ flight.departure_format }}</span></h4>
				</div>
				<!-- COL ENDS -->

				<!-- COL STARTS -->
				<div class="col-md-12 mb-3 text-left">
					<h4>Estimated arrival in {{ flight.destination }} <span class="red-text">{{ flight.get_arrival_time }}</span></h4>
				</div>
				<!-- COL ENDS -->

				<!-- col starts -->
				<div class="col-md-6 mb-3 text-left">
					<h4><a href="{% url 'passenger-list' %}">Flight Passengers</a></h4>
				</div>
				<!-- col ends -->

			</div>
			<!-- ROW ENDS -->

		</div>
		<!-- ROW ENDS -->

	</section>
	<!-- /SECTION: FLIGHTS -->
{% endblock content %}

templates/flights/flight_confirm_delete.html
{% extends "base.html" %}

{% block title %}
	Delete Flight
{% endblock %}

{% block content %}

	<div class="container mt-5 mb-4 text-center">
		<h1 class="red-text mb-4">Delete Flight</h1>
		<p class="mb-4">Are you sure you want to delete the flight: <span class="text-danger">{{ flight }}</span> ?</p>
		<p class="text-info mb-4">The action is permanent</p>
		<form class="mb-4" action="" method="post" accept-charset="utf-8">
			{% csrf_token %}
			<button type="submit" class="btn btn-danger">Confirm</button>
		</form>
	</div>

{% endblock %}

templates/flights/flight_detail.html
{% extends "base.html" %}

{% block title %}
	Flights Detail
{% endblock title %}

{% block content %}
	<!-- SECTION: FLIGHTS -->
	<section class="container mt-5">
		
		<h3 class="orange-text text-left pl-3 mb-4">Flight Details</h3>
		
		<!-- ROW STARTS -->
		<div class="row container">

			<!-- COL STARTS -->
			<div class="col-md-4 text-left">
				<h4>From: <span class="green-text">{{ flight.origin|title }}</span></h4>
			</div>
			<!-- COL ENDS -->

			<!-- COL STARTS -->
			<div class="col-md-4 text-left">
				<h4>To: <span class="green-text">{{ flight.destination|title }}</span></h4>
			</div>
			<!-- COL ENDS -->

			<!-- COL STARTS -->
			<div class="col-md-4 text-left">
				<h4>Duration: <span class="grey-text">{{ flight.duration }}<span></h4>
			</div>
			<!-- COL ENDS -->

			<!-- ROW STARTS -->
			<div class="row container mt-3">

				<!-- COL STARTS -->
				<div class="col-md-12 mb-3 text-left">
					<h4>Departure from {{ flight.origin }}: <span class="blue-text">{{ flight.departure_format }}</span></h4>
				</div>
				<!-- COL ENDS -->

				<!-- COL STARTS -->
				<div class="col-md-12 text-left">
					<h4>Estimated arrival in {{ flight.destination }} <span class="red-text">{{ flight.get_arrival_time }}</span></h4>
				</div>
				<!-- COL ENDS -->

			</div>
			<!-- ROW ENDS -->

		</div>
		<!-- ROW ENDS -->

	</section>
	<!-- /SECTION: FLIGHTS -->
{% endblock content %}

templates/flights/flight_form.html
{% extends "base.html" %}

{% block title %}
	Create Flight
{% endblock title %}

{% block content %}

	<div class="container mt-5">
		
		<form action="" method="post" accept-charset="utf-8">
			{% csrf_token %}
			<table class="mb-3 table">
				{{ form }}
			</table>
			<input type='submit' value='Submit'>
		</form>

{% endblock content %}

templates/flights/flights_list.html
{% extends "base.html" %}

{% block title %}
	All Flights
{% endblock title %}

{% block content %}
	<!-- SECTION: FLIGHTS -->
    <div class="mt-5 mb-5 container">
    	{% for flight in flight_list %}
	    
	    	<!--Panel-->
	    	<div class="card w-75 mb-4">
		        <div class="card-body">
		            <h5 class="card-title">₹ {{ flight.price }}</h5>
		            <p class="card-text">Cheapest flight from {{ flight.origin }} to {{ flight.destination }}</p>

		            {% if flight.has_departed %}
		            	<a href="{% url 'contact_form' %}" class="btn btn-danger">Details</a>
		            {% else %}
		            	<a href="{{ flight.get_absolute_url }}" class="btn btn-success">
		            	Details</a>
		            {% endif %}
		        </div>
		        <div class="card-footer">
		            <small class="text-muted">
		            	{% if flight.has_departed %}
		            		Departed...
		            	{% else %}
		            	 	Departure on {{ flight.get_departure_time }}...
						{% endif %}
		            </small>
		        </div>
			</div>
			<!--/.Panel-->
		
		{% endfor %}
	</div>

	<!-- /SECTION: FLIGHTS -->
{% endblock content %}

templates/flights/home_page.html
{% extends "base.html" %}
{% load static %}
{% block title %}
	Best Flights In Django
{% endblock title %}

{% block content %}
    <div class="site-blocks-cover" style="background-image: url('{{STATIC_URL}}/images/hero_bg_1.jpg');" data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row row-custom align-items-center">
          <div class="col-md-10">
            <h1 class="mb-2 text-black w-75"><span class="font-weight-bold">Largest Job</span> Site On The Net</h1>
            <div class="job-search">
              <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active py-3" id="pills-job-tab" data-toggle="pill" href="#pills-job" role="tab" aria-controls="pills-job" aria-selected="true">Find A Job</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link py-3" id="pills-candidate-tab" data-toggle="pill" href="#pills-candidate" role="tab" aria-controls="pills-candidate" aria-selected="false">Find A Candidate</a>
                </li>
              </ul>
              <div class="tab-content bg-white p-4 rounded" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-job" role="tabpanel" aria-labelledby="pills-job-tab">
                  <form action="#" method="post">
                    <div class="row">
                      <div class="col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <input type="text" class="form-control" placeholder="eg. Web Developer">
                      </div>
                      <div class="col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <div class="select-wrap">
                          <span class="icon-keyboard_arrow_down arrow-down"></span>
                          <select name="" id="" class="form-control">
                            <option value="">Category</option>
                            <option value="fulltime">Full Time</option>
                            <option value="fulltime">Part Time</option>
                            <option value="freelance">Freelance</option>
                            <option value="internship">Internship</option>
                            <option value="internship">Termporary</option>
                          </select>
                        </div>
                      </div>
                      <div class="col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <input type="text" class="form-control form-control-block search-input" id="autocomplete" placeholder="Location" onFocus="geolocate()">
                      </div>
                      <div class="col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <input type="submit" class="btn btn-primary btn-block" value="Search">
                      </div>
                    </div>
                  </form>
                </div>
                <div class="tab-pane fade" id="pills-candidate" role="tabpanel" aria-labelledby="pills-candidate-tab">
                  <form action="#" method="post">
                    <div class="row">
                      <div class="col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <input type="text" class="form-control" placeholder="eg. Carl Smith">
                      </div>
                      <div class="col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <div class="select-wrap">
                          <span class="icon-keyboard_arrow_down arrow-down"></span>
                          <select name="" id="" class="form-control">
                            <option value="">Category</option>
                            <option value="fulltime">Full Time</option>
                            <option value="fulltime">Part Time</option>
                            <option value="freelance">Freelance</option>
                            <option value="internship">Internship</option>
                            <option value="internship">Termporary</option>
                          </select>
                        </div>
                      </div>
                      <div class="col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <input type="text" class="form-control form-control-block search-input" id="autocomplete" placeholder="Location" onFocus="geolocate()">
                      </div>
                      <div class="col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <input type="submit" class="btn btn-primary btn-block" value="Search">
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>  
    

	
	<div class="site-section bg-light">
      <div class="container">
        <div class="row justify-content-start text-left mb-5">
          <div class="col-md-9" data-aos="fade">
            <h2 class="font-weight-bold text-black">Recent Flights</h2>
          </div>
          <div class="col-md-3" data-aos="fade" data-aos-delay="200">
            <a href="#" class="btn btn-primary py-3 btn-block"><span class="h5">+</span> Flight updates</a>
          </div>
        </div>
        <div class="row" data-aos="fade">
         <div class="col-md-12">
         			
        {% for flight in flight_list %}
		           <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">

		              <div class="mb-4 mb-md-0 mr-5">
		               <div class="job-post-item-header d-flex align-items-center">
		                 <h2 class="mr-3 text-black h4">{{ flight.origin }} to {{ flight.destination }}</h2>
		                 <div class="badge-wrap">
		                  <span class="bg-primary text-white badge py-2 px-4">{{ flight.price }}</span>
		                 </div>
		               </div>
		               <div class="job-post-item-body d-block d-md-flex">
		                 <div class="mr-3"><span class="fl-bigmug-line-portfolio23"></span> <a href="#">Facebook, Inc.</a></div>
		                 <div><span class="fl-bigmug-line-big104"></span> <span>Flight Duration: {{ flight.duration }}</span></div>
		               </div>
		              </div>

		              <div class="ml-auto">
		              	{% if flight.has_departed %}
		              	<a href="#" class="btn btn-secondary rounded-circle btn-favorite text-gray-500"><span class="icon-heart"></span></a>
		                <a href="{% url 'contact_form' %}" class="btn btn-primary py-2">Departed</a>
				{% else %}
				<a href="#" class="btn btn-secondary rounded-circle btn-favorite text-gray-500"><span class="icon-heart"></span></a>
		                <a href="{{ flight.get_absolute_url }}" class="btn btn-primary py-2">Book now</a>
		    	{% endif %}
		                
		              </div>
		           </div>
			{% endfor %}
         </div>
        </div>
    </div>
</div>
	<!-- MAIN PAGE -->
{% endblock content %}

templates/flights/search_results.html
{% extends "base.html" %}

{% block title %}
	Search Results
{% endblock %}

{% block content %}

	<div class="container mt-5">
		<h2 class="" aria-label="Search">You searched for {{ query }}</h2>
	</div>

{% endblock %}